name: Dispatcher to run demoblaze test on staging environment
on:
  push:
    branches:
      - feature/DispatcherTest
  workflow_dispatch:

jobs:
  execute-dispatcher-test:
    name: Execute dispatcher test
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: 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
          repository: yesidhernandez/BDDAutomationDemoblaze
          event-type: run-demoblaze-scenarios-on-staging